# Generated by Django 5.2.4 on 2025-07-27 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0001_initial'),
        ('users', '0002_food_allergen_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.ManyToManyField(to='allergies.allergy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('patient', 'Patient')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food_allergen',
            name='allergy_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ManyToManyField(to='users.menu_section')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.menu_section'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'restaurant'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu_section',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
    ]
