# Generated by Django 5.2.4 on 2025-08-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_menu_section_customuser_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food_allergen',
            name='allergy_name',
        ),
        migrations.RemoveField(
            model_name='menu_section',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='food_allergen',
            name='allergen',
            field=models.CharField(choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('treenuts', 'Treenuts'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat'), ('soybeans', 'Soybeans'), ('sesame', 'Sesame'), ('fish', 'Fish')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='users.restaurant'),
        ),
    ]
