# Generated by Django 5.2.4 on 2025-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergyname',
            field=models.CharField(choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('treenuts', 'Treenuts'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat'), ('soybeans', 'Soybeans'), ('sesame', 'Sesame'), ('fish', 'Fish')], max_length=255, null=True),
        ),
    ]
